# Dependabot will run on day 26 of each month at 03:14 (Europe/Berlin timezone)
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "14 3 26 * *"
    open-pull-requests-limit: 15
    assignees:
      - "hacki11"
    versioning-strategy: "increase"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "14 3 26 * *"
    open-pull-requests-limit: 15
    assignees:
      - "hacki11"
